<?php

namespace Database\Seeders;

use App\Models\Doctor;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        $doctors = [
            [
                'name' => 'Feruza',
                'middle_name' => 'Davronovna',
                'last_name' => 'Salomova',
                'email' => 'feruza.salomova@gmail.com',
                'phone' => '+998901234567',
                'gender' => 'female',
                'birth_date' => '1985-03-15',
                'passport_series' => 'AA5938271',
                'passport_number' => '12389045761234',
                'address' => 'Toshkent, Chilonzor',
                'specialization' => 'Pediatr',
                'position' => "Bo'lim boshlig'i",
                'qualification' => 'Yuqori malaka',
                'experience_years' => 15,
                'graduation_date' => '2008-06-20',
                'hire_date' => '2019-10-20',
                'bio' => "15 yillik pediatr. Bolalar kasalliklari bo'yicha katta tajriba.",
                'photo' => 'doctors/Feruza.jpg',
            ],
            [
                'name' => 'Javlon',
                'middle_name' => 'Bekzodovich',
                'last_name' => 'Usmonov',
                'email' => 'jusmonov82@gmail.com',
                'phone' => '+998901112233',
                'gender' => 'male',
                'birth_date' => '1982-01-10',
                'passport_series' => 'AB9045126',
                'passport_number' => '98765412034811',
                'address' => 'Toshkent, Mirzo Ulug\'bek',
                'specialization' => 'Kardiolog',
                'position' => 'Yuqori toifali shifokor',
                'qualification' => 'Kardiologiya sertifikati',
                'experience_years' => 18,
                'graduation_date' => '2005-06-15',
                'hire_date' => '2018-06-10',
                'bio' => "18 yillik tajribaga ega kardiolog.",
                'photo' => 'doctors/Javlon.jpg',
            ],
            [
                'name' => 'Madina',
                'middle_name' => 'Saidovna',
                'last_name' => 'Karimova',
                'email' => 'madina_karimova90@gmail.com',
                'phone' => '+998909998877',
                'gender' => 'female',
                'birth_date' => '1990-07-20',
                'passport_series' => 'AC7182049',
                'passport_number' => '56789012345789',
                'address' => 'Toshkent, Yakkasaroy',
                'specialization' => 'Dermatolog',
                'position' => 'Shifokor',
                'qualification' => 'Dermatologiya oliy toifa',
                'experience_years' => 10,
                'graduation_date' => '2013-06-25',
                'hire_date' => '2020-01-10',
                'bio' => "Teri kasalliklari bo'yicha 10 yillik tajriba.",
                'photo' => 'doctors/Madina.jpg',
            ],
            [
                'name' => 'Dilshod',
                'middle_name' => 'Komilovich',
                'last_name' => 'Raximov',
                'email' => 'dr.dilshod88@gmail.com',
                'phone' => '+998909901122',
                'gender' => 'male',
                'birth_date' => '1988-11-02',
                'passport_series' => 'AD3259814',
                'passport_number' => '76012984561230',
                'address' => 'Samarqand, Narpay',
                'specialization' => 'Nevropatolog',
                'position' => 'Shifokor',
                'qualification' => 'Nevrologiya sertifikati',
                'experience_years' => 12,
                'graduation_date' => '2010-06-30',
                'hire_date' => '2021-03-02',
                'bio' => "Nerv tizimi kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Dilshod.jpg',
            ],
            [
                'name' => 'Lola',
                'middle_name' => 'Olimovna',
                'last_name' => 'Nazarova',
                'email' => 'lolanazarova87@gmail.com',
                'phone' => '+998903334455',
                'gender' => 'female',
                'birth_date' => '1987-04-12',
                'passport_series' => 'AE6597203',
                'passport_number' => '89013456278901',
                'address' => 'Buxoro, G\'ijduvon',
                'specialization' => 'Ginekolog',
                'position' => 'Bo\'lim shifokori',
                'qualification' => 'Ginekologiya sertifikati',
                'experience_years' => 14,
                'graduation_date' => '2009-06-29',
                'hire_date' => '2017-01-18',
                'bio' => "Ayollar salomatligi bo'yicha ko'p yillik tajriba.",
                'photo' => 'doctors/Lola.jpg',
            ],
            [
                'name' => 'Aziza',
                'middle_name' => 'Erkinovna',
                'last_name' => 'Hoshimova',
                'email' => 'aziza.h95@gmail.com',
                'phone' => '+998909876543',
                'gender' => 'female',
                'birth_date' => '1995-05-05',
                'passport_series' => 'AF7890123',
                'passport_number' => '65432109876543',
                'address' => 'Toshkent, Sergeli',
                'specialization' => 'Gastroenterolog',
                'position' => 'Shifokor',
                'qualification' => 'Gastroenterologiya sertifikati',
                'experience_years' => 7,
                'graduation_date' => '2016-06-15',
                'hire_date' => '2021-01-10',
                'bio' => "Ovqat hazm qilish tizimi kasalliklari bo'yicha tajribaga ega shifokor.",
                'photo' => 'doctors/Aziza.jpg',
            ],
            [
                'name' => 'Temur',
                'middle_name' => 'Azamatovich',
                'last_name' => 'Qodirov',
                'email' => 'temurq83@gmail.com',
                'phone' => '+998901234890',
                'gender' => 'male',
                'birth_date' => '1983-09-15',
                'passport_series' => 'AG0928374',
                'passport_number' => '98765432109876',
                'address' => 'Samarqand, Shahrisabz',
                'specialization' => 'Onkolog',
                'position' => 'Yuqori toifali shifokor',
                'qualification' => 'Onkologiya sertifikati',
                'experience_years' => 16,
                'graduation_date' => '2007-04-15',
                'hire_date' => '2019-05-20',
                'bio' => "Onkologik kasalliklarni davolashda katta tajribaga ega.",
                'photo' => 'doctors/Temur.jpg',
            ],
            [
                'name' => 'Gulnur',
                'middle_name' => 'Rashidovna',
                'last_name' => 'Jumayeva',
                'email' => 'gulnurj92@gmail.com',
                'phone' => '+998908765432',
                'gender' => 'female',
                'birth_date' => '1992-12-25',
                'passport_series' => 'AH1234567',
                'passport_number' => '23456789012345',
                'address' => 'Toshkent, Yashnabad',
                'specialization' => 'Reabilitolog',
                'position' => 'Shifokor',
                'qualification' => 'Reabilitologiya sertifikati',
                'experience_years' => 5,
                'graduation_date' => '2018-05-20',
                'hire_date' => '2021-06-01',
                'bio' => "Reabilitologiya sohasida 5 yil tajribaga ega.",
                'photo' => 'doctors/Gulnur.jpg',
            ],
            [
                'name' => 'Farhod',
                'middle_name' => 'Baxromovich',
                'last_name' => 'To\'raev',
                'email' => 'dr.farhod86@gmail.com',
                'phone' => '+998901234098',
                'gender' => 'male',
                'birth_date' => '1986-03-30',
                'passport_series' => 'AK6543210',
                'passport_number' => '34567890123456',
                'address' => 'Sirdaryo, Guliston',
                'specialization' => 'Urolog',
                'position' => 'Shifokor',
                'qualification' => 'Urologiya sertifikati',
                'experience_years' => 12,
                'graduation_date' => '2011-05-05',
                'hire_date' => '2020-01-30',
                'bio' => "Urologik kasalliklarni davolashda 12 yillik tajribaga ega.",
                'photo' => 'doctors/Farhod.jpg',
            ],
            [
                'name' => 'Nodira',
                'middle_name' => 'Rustamovna',
                'last_name' => 'Sirojiddinova',
                'email' => 'sirojiddinova.nodira@gmail.com',
                'phone' => '+998902233445',
                'gender' => 'female',
                'birth_date' => '1994-08-18',
                'passport_series' => 'AL9876543',
                'passport_number' => '45678901234567',
                'address' => 'Toshkent, Olmazor',
                'specialization' => 'Oftalmolog',
                'position' => 'Bo\'lim shifokori',
                'qualification' => 'Oftalmologiya oliy toifa',
                'experience_years' => 6,
                'graduation_date' => '2017-06-30',
                'hire_date' => '2021-08-15',
                'bio' => "Ko'z kasalliklari bo'yicha 6 yillik tajribaga ega shifokor.",
                'photo' => 'doctors/Nodira.jpg',
            ],
            [
                'name' => 'Shahnoza',
                'middle_name' => 'Baxtiyorovna',
                'last_name' => 'Aliyeva',
                'email' => 'shahnoza_aliyeva89@gmail.com',
                'phone' => '+998907778899',
                'gender' => 'female',
                'birth_date' => '1989-09-10',
                'passport_series' => 'AM2345678',
                'passport_number' => '56789012345678',
                'address' => 'Toshkent, Yunusobod',
                'specialization' => 'Endokrinolog',
                'position' => 'Shifokor',
                'qualification' => 'Endokrinologiya sertifikati',
                'experience_years' => 8,
                'graduation_date' => '2015-06-20',
                'hire_date' => '2022-02-01',
                'bio' => "Endokrin tizim kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Shahnoza.jpg',
            ],
            [
                'name' => 'Rustam',
                'middle_name' => 'Sultonovich',
                'last_name' => 'Abdullayev',
                'email' => 'rustamabdullayev84@gmail.com',
                'phone' => '+998905556677',
                'gender' => 'male',
                'birth_date' => '1984-06-25',
                'passport_series' => 'AN3456789',
                'passport_number' => '67890123456789',
                'address' => 'Samarqand, Bulungur',
                'specialization' => 'Ortoped',
                'position' => 'Bo\'lim boshlig\'i',
                'qualification' => 'Ortopediya oliy toifa',
                'experience_years' => 14,
                'graduation_date' => '2009-06-15',
                'hire_date' => '2016-09-01',
                'bio' => "Ortopediya sohasida katta tajribaga ega shifokor.",
                'photo' => 'doctors/Rustam.jpg',
            ],
            [
                'name' => 'Dilobar',
                'middle_name' => 'Anvarovna',
                'last_name' => 'Tursunova',
                'email' => 'dilobar.t91@gmail.com',
                'phone' => '+998902223344',
                'gender' => 'female',
                'birth_date' => '1991-11-12',
                'passport_series' => 'AP4567890',
                'passport_number' => '78901234567890',
                'address' => 'Toshkent, Mirobod',
                'specialization' => 'Psixiatr',
                'position' => 'Shifokor',
                'qualification' => 'Psixiatriya sertifikati',
                'experience_years' => 6,
                'graduation_date' => '2017-06-25',
                'hire_date' => '2023-01-15',
                'bio' => "Ruhiy salomatlik va psixologik kasalliklarni davolash bo'yicha mutaxassis.",
                'photo' => 'doctors/Dilobar.jpg',
            ],
            [
                'name' => 'Sardor',
                'middle_name' => 'Xudoyberdiyevich',
                'last_name' => 'Muxammedov',
                'email' => 'sardor.m87@gmail.com',
                'phone' => '+998901212334',
                'gender' => 'male',
                'birth_date' => '1987-07-18',
                'passport_series' => 'AQ5678901',
                'passport_number' => '89012345678901',
                'address' => 'Farg\'ona, Marg\'ilon',
                'specialization' => 'Oftalmolog',
                'position' => 'Yuqori toifali shifokor',
                'qualification' => 'Oftalmologiya sertifikati',
                'experience_years' => 11,
                'graduation_date' => '2012-06-28',
                'hire_date' => '2020-03-10',
                'bio' => "Ko'z kasalliklari bo'yicha 11 yillik tajriba.",
                'photo' => 'doctors/Sardor.jpg',
            ],
            [
                'name' => 'Gulchehra',
                'middle_name' => 'Raxmonovna',
                'last_name' => 'Ismoilova',
                'email' => 'gulchehra_i86@gmail.com',
                'phone' => '+998908889900',
                'gender' => 'female',
                'birth_date' => '1986-02-28',
                'passport_series' => 'AR6789012',
                'passport_number' => '90123456789012',
                'address' => 'Toshkent, Olmazor',
                'specialization' => 'Nevrolog',
                'position' => 'Shifokor',
                'qualification' => 'Nevrologiya sertifikati',
                'experience_years' => 13,
                'graduation_date' => '2010-06-22',
                'hire_date' => '2018-11-05',
                'bio' => "Nerv tizimi kasalliklarini davolash bo'yicha mutaxassis.",
                'photo' => 'doctors/Gulchehra.jpg',
            ],
            [
                'name' => 'Zokir',
                'middle_name' => 'Xamidovich',
                'last_name' => 'Raximov',
                'email' => 'dr.zokir90@gmail.com',
                'phone' => '+998903334422',
                'gender' => 'male',
                'birth_date' => '1990-10-08',
                'passport_series' => 'AS7890123',
                'passport_number' => '01234567890123',
                'address' => 'Buxoro, Kogon',
                'specialization' => 'Urolog',
                'position' => 'Shifokor',
                'qualification' => 'Urologiya sertifikati',
                'experience_years' => 8,
                'graduation_date' => '2015-06-18',
                'hire_date' => '2021-07-01',
                'bio' => "Urologiya sohasida 8 yillik tajribaga ega shifokor.",
                'photo' => 'doctors/Zokir.jpg',
            ],
            [
                'name' => 'Maftuna',
                'middle_name' => 'Nodirovna',
                'last_name' => 'Qodirova',
                'email' => 'maftuna.q93@gmail.com',
                'phone' => '+998909988776',
                'gender' => 'female',
                'birth_date' => '1993-04-15',
                'passport_series' => 'AT8901234',
                'passport_number' => '12345678901234',
                'address' => 'Toshkent, Chilonzor',
                'specialization' => 'Gastroenterolog',
                'position' => 'Shifokor',
                'qualification' => 'Gastroenterologiya sertifikati',
                'experience_years' => 5,
                'graduation_date' => '2018-06-30',
                'hire_date' => '2023-02-15',
                'bio' => "Ovqat hazm qilish tizimi kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Maftuna.jpg',
            ],
            [
                'name' => 'Sobir',
                'middle_name' => 'Erkinovich',
                'last_name' => 'Toshmatov',
                'email' => 'sobir.toshmatov@gmail.com',
                'phone' => '+998902233466',
                'gender' => 'male',
                'birth_date' => '1981-12-01',
                'passport_series' => 'AU9012345',
                'passport_number' => '23456789012345',
                'address' => 'Qashqadaryo, Qarshi',
                'specialization' => 'Kardiolog',
                'position' => 'Bo\'lim boshlig\'i',
                'qualification' => 'Kardiologiya oliy toifa',
                'experience_years' => 17,
                'graduation_date' => '2006-06-10',
                'hire_date' => '2015-01-20',
                'bio' => "Kardiologiya sohasida katta tajriba va yuqori malaka.",
                'photo' => 'doctors/Sobir.jpg',
            ],
            [
                'name' => 'Nilufar',
                'middle_name' => 'Tolibovna',
                'last_name' => 'Mirzayeva',
                'email' => 'nilufar_m88@gmail.com',
                'phone' => '+998903445566',
                'gender' => 'female',
                'birth_date' => '1988-08-22',
                'passport_series' => 'AV0123456',
                'passport_number' => '34567890123456',
                'address' => 'Toshkent, Yakkasaroy',
                'specialization' => 'Dermatolog',
                'position' => 'Shifokor',
                'qualification' => 'Dermatologiya sertifikati',
                'experience_years' => 9,
                'graduation_date' => '2014-06-25',
                'hire_date' => '2021-04-01',
                'bio' => "Teri kasalliklarini davolash bo'yicha mutaxassis.",
                'photo' => 'doctors/Nilufar.jpg',
            ],
            [
                'name' => 'Baxrom',
                'middle_name' => 'Rustamovich',
                'last_name' => 'Yo\'ldoshev',
                'email' => 'baxrom_y85@gmail.com',
                'phone' => '+998901234789',
                'gender' => 'male',
                'birth_date' => '1985-05-14',
                'passport_series' => 'AW1234567',
                'passport_number' => '45678901234567',
                'address' => 'Navoiy, Navoiy shahri',
                'specialization' => 'Onkolog',
                'position' => 'Shifokor',
                'qualification' => 'Onkologiya sertifikati',
                'experience_years' => 10,
                'graduation_date' => '2013-06-20',
                'hire_date' => '2022-06-01',
                'bio' => "Onkologik kasalliklar bo'yicha 10 yillik tajriba.",
                'photo' => 'doctors/Baxrom.jpg',
            ],
            [
                'name' => 'Durdona',
                'middle_name' => 'Baxodirovna',
                'last_name' => 'Xoshimova',
                'email' => 'durdona.x96@gmail.com',
                'phone' => '+998907654321',
                'gender' => 'female',
                'birth_date' => '1996-06-30',
                'passport_series' => 'AX2345678',
                'passport_number' => '56789012345678',
                'address' => 'Toshkent, Sergeli',
                'specialization' => 'Pediatr',
                'position' => 'Shifokor',
                'qualification' => 'Pediatriya sertifikati',
                'experience_years' => 4,
                'graduation_date' => '2019-06-28',
                'hire_date' => '2023-03-01',
                'bio' => "Bolalar kasalliklari bo'yicha yosh mutaxassis.",
                'photo' => 'doctors/Durdona.jpg',
            ],
            [
                'name' => 'Nuriddin',
                'middle_name' => 'Sodiqovich',
                'last_name' => 'Hasanov',
                'email' => 'nuriddin.h89@gmail.com',
                'phone' => '+998905544331',
                'gender' => 'male',
                'birth_date' => '1989-02-19',
                'passport_series' => 'AY3456789',
                'passport_number' => '67890123456789',
                'address' => 'Andijon, Andijon shahri',
                'specialization' => 'Nevropatolog',
                'position' => 'Shifokor',
                'qualification' => 'Nevrologiya sertifikati',
                'experience_years' => 7,
                'graduation_date' => '2016-06-22',
                'hire_date' => '2021-09-15',
                'bio' => "Nerv tizimi kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Nuriddin.jpg',
            ],
            [
                'name' => 'Sevara',
                'middle_name' => 'Shavkatovna',
                'last_name' => 'Raximjonova',
                'email' => 'sevara.r92@gmail.com',
                'phone' => '+998901234567',
                'gender' => 'female',
                'birth_date' => '1992-09-05',
                'passport_series' => 'AZ4567890',
                'passport_number' => '78901234567890',
                'address' => 'Toshkent, Shayxontohur',
                'specialization' => 'Ginekolog',
                'position' => 'Shifokor',
                'qualification' => 'Ginekologiya sertifikati',
                'experience_years' => 5,
                'graduation_date' => '2018-06-29',
                'hire_date' => '2022-08-01',
                'bio' => "Ayollar salomatligi bo'yicha mutaxassis.",
                'photo' => 'doctors/Sevara.jpg',
            ],
            [
                'name' => 'Akmal',
                'middle_name' => 'Karimovich',
                'last_name' => 'Sultanov',
                'email' => 'akmal.s83@gmail.com',
                'phone' => '+998909887766',
                'gender' => 'male',
                'birth_date' => '1983-07-07',
                'passport_series' => 'BA5678901',
                'passport_number' => '89012345678901',
                'address' => 'Samarqand, Samarqand shahri',
                'specialization' => 'Ortoped',
                'position' => 'Yuqori toifali shifokor',
                'qualification' => 'Ortopediya sertifikati',
                'experience_years' => 14,
                'graduation_date' => '2009-06-18',
                'hire_date' => '2017-04-01',
                'bio' => "Ortopediya va travmatologiya bo'yicha mutaxassis.",
                'photo' => 'doctors/Akmal.jpg',
            ],
            [
                'name' => 'Dilfuza',
                'middle_name' => 'Ergashevna',
                'last_name' => 'Muxamedova',
                'email' => 'dilfuza.m90@gmail.com',
                'phone' => '+998903223344',
                'gender' => 'female',
                'birth_date' => '1990-12-12',
                'passport_series' => 'BB6789012',
                'passport_number' => '90123456789012',
                'address' => 'Toshkent, Mirobod',
                'specialization' => 'Endokrinolog',
                'position' => 'Shifokor',
                'qualification' => 'Endokrinologiya sertifikati',
                'experience_years' => 6,
                'graduation_date' => '2017-06-26',
                'hire_date' => '2023-01-01',
                'bio' => "Endokrin kasalliklarni davolash bo'yicha mutaxassis.",
                'photo' => 'doctors/Dilfuza.jpg',
            ],
            [
                'name' => 'Olim',
                'middle_name' => 'Abdurahmonovich',
                'last_name' => 'Valiyev',
                'email' => 'olim_valiyev86@gmail.com',
                'phone' => '+998901232345',
                'gender' => 'male',
                'birth_date' => '1986-04-02',
                'passport_series' => 'BC7890123',
                'passport_number' => '01234567890123',
                'address' => 'Farg\'ona, Quva',
                'specialization' => 'Pulmonolog',
                'position' => 'Shifokor',
                'qualification' => 'Pulmonologiya sertifikati',
                'experience_years' => 10,
                'graduation_date' => '2013-06-30',
                'hire_date' => '2020-05-10',
                'bio' => "Nafas olish tizimi kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Olim.jpg',
            ],
            [
                'name' => 'Muhabbat',
                'middle_name' => 'Mamatqulovna',
                'last_name' => 'Bobojonova',
                'email' => 'muhabbat_b91@gmail.com',
                'phone' => '+998905566778',
                'gender' => 'female',
                'birth_date' => '1991-03-07',
                'passport_series' => 'BD8901234',
                'passport_number' => '12345678901234',
                'address' => 'Xorazm, Urganch',
                'specialization' => 'Oftalmolog',
                'position' => 'Shifokor',
                'qualification' => 'Oftalmologiya sertifikati',
                'experience_years' => 5,
                'graduation_date' => '2018-06-28',
                'hire_date' => '2022-04-01',
                'bio' => "Ko'z kasalliklari bo'yicha mutaxassis.",
                'photo' => 'doctors/Muhabbat.jpg',
            ],
            [
                'name' => 'Jasur',
                'middle_name' => 'Xolmurodovich',
                'last_name' => 'Rahimov',
                'email' => 'jasur.r87@gmail.com',
                'phone' => '+998901123456',
                'gender' => 'male',
                'birth_date' => '1987-06-14',
                'passport_series' => 'BE9012345',
                'passport_number' => '23456789012345',
                'address' => 'Surxondaryo, Termiz',
                'specialization' => 'Kardiolog',
                'position' => 'Shifokor',
                'qualification' => 'Kardiologiya sertifikati',
                'experience_years' => 8,
                'graduation_date' => '2015-06-20',
                'hire_date' => '2021-11-01',
                'bio' => "Kardiologiya sohasida 8 yillik tajribaga ega shifokor.",
                'photo' => 'doctors/Jasur.jpg',
            ],
            [
                'name' => 'Yulduz',
                'middle_name' => 'Alisherovna',
                'last_name' => 'Xolmatova',
                'email' => 'yulduz_xolmatova@gmail.com',
                'phone' => '+998909988665',
                'gender' => 'female',
                'birth_date' => '1993-11-20',
                'passport_series' => 'BF0123456',
                'passport_number' => '34567890123456',
                'address' => 'Toshkent, Chilonzor',
                'specialization' => 'Nevrolog',
                'position' => 'Shifokor',
                'qualification' => 'Nevrologiya sertifikati',
                'experience_years' => 4,
                'graduation_date' => '2019-06-25',
                'hire_date' => '2023-04-01',
                'bio' => "Nevrologiya sohasida yosh mutaxassis.",
                'photo' => 'doctors/Yulduz.jpg',
            ],
            [
                'name' => 'Sherzod',
                'middle_name' => 'Baxodirovich',
                'last_name' => 'Mamatov',
                'email' => 'sherzod_m85@gmail.com',
                'phone' => '+998901232344',
                'gender' => 'male',
                'birth_date' => '1985-08-25',
                'passport_series' => 'BG1234567',
                'passport_number' => '45678901234567',
                'address' => 'Jizzax, Jizzax shahri',
                'specialization' => 'Ortoped',
                'position' => 'Shifokor',
                'qualification' => 'Ortopediya sertifikati',
                'experience_years' => 11,
                'graduation_date' => '2012-06-30',
                'hire_date' => '2020-07-01',
                'bio' => "Ortopedik kasalliklarni davolash bo'yicha mutaxassis.",
                'photo' => 'doctors/Sherzod.jpg',
            ],
            [
                'name' => 'Zarina',
                'middle_name' => 'Ikromovna',
                'last_name' => 'Ochilova',
                'email' => 'zarina_ochilova94@gmail.com',
                'phone' => '+998907778866',
                'gender' => 'female',
                'birth_date' => '1994-02-28',
                'passport_series' => 'BH2345678',
                'passport_number' => '56789012345678',
                'address' => 'Toshkent, Yunusobod',
                'specialization' => 'Ginekolog',
                'position' => 'Shifokor',
                'qualification' => 'Ginekologiya sertifikati',
                'experience_years' => 4,
                'graduation_date' => '2019-06-30',
                'hire_date' => '2023-05-01',
                'bio' => "Ayollar salomatligi bo'yicha yosh mutaxassis.",
                'photo' => 'doctors/Zarina.jpg',
            ]
        ];

        $login = 440231101000;

        foreach ($doctors as $d) {
            $user = User::create([
                'name' => $d['name'],
                'middle_name' => $d['middle_name'],
                'last_name' => $d['last_name'],
                'login' => (string)$login,
                'email' => $d['email'],
                'phone' => $d['phone'],
                'password' => Hash::make('secret'),
                'is_active' => 1
            ]);

            Doctor::create([
                'user_id' => $user->id,
                'birth_date' => $d['birth_date'],
                'gender' => $d['gender'],
                'passport_series' => $d['passport_series'],
                'passport_number' => $d['passport_number'],
                'address' => $d['address'],
                'specialization' => $d['specialization'],
                'position' => $d['position'],
                'qualification' => $d['qualification'],
                'experience_years' => $d['experience_years'],
                'graduation_date' => $d['graduation_date'],
                'hire_date' => $d['hire_date'],
                'bio' => $d['bio'],
                'status' => 'active',
                'photo' => $d['photo'],
            ]);

            if (method_exists($user, 'roles')) {
                $user->roles()->sync([2]);
            }

            $login++;
        }
    }
}