<?php

namespace Database\Seeders;

use App\Models\Procedure;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProcedureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $procedures = [

            // ==================== KARDIOLOGIYA ====================
            [
                'department_id' => 1,
                'name_uz' => 'Elektrokardiografiya (EKG)',
                'name_ru' => 'Электрокардиография (ЭКГ)',
                'name_en' => 'Electrocardiography (ECG)',
                'category' => 'diagnostic',
                'price' => 20.00,
                'duration' => 15,
                'description_uz' => 'Yurak elektr faolligini tekshirish.',
                'description_ru' => 'Исследование электрической активности сердца.',
                'description_en' => 'Examination of the electrical activity of the heart.',
                'is_active' => true,
            ],
            [
                'department_id' => 1,
                'name_uz' => 'Xolter monitoring',
                'name_ru' => 'Холтеровское мониторирование',
                'name_en' => 'Holter Monitoring',
                'category' => 'diagnostic',
                'price' => 45.00,
                'duration' => 30,
                'description_uz' => '24 soatlik yurak ritmini kuzatish.',
                'description_ru' => '24-часовое наблюдение за сердечным ритмом.',
                'description_en' => '24-hour heart rhythm monitoring.',
                'is_active' => true,
            ],
            [
                'department_id' => 1,
                'name_uz' => 'Stress testi',
                'name_ru' => 'Стресс-тест',
                'name_en' => 'Stress Test',
                'category' => 'diagnostic',
                'price' => 50.00,
                'duration' => 40,
                'description_uz' => 'Jismoniy yuklama ostida yurak faoliyatini tekshirish.',
                'description_ru' => 'Проверка работы сердца при физической нагрузке.',
                'description_en' => 'Heart examination during physical activity.',
                'is_active' => true,
            ],
        
            // ==================== NEVROLOGIYA ====================
            [
                'department_id' => 2,
                'name_uz' => 'Elektroforez',
                'name_ru' => 'Электрофорез',
                'name_en' => 'Electrophoresis',
                'category' => 'therapy',
                'price' => 18.00,
                'duration' => 20,
                'description_uz' => 'Elektr toki yordamida davolash.',
                'description_ru' => 'Лечение с помощью электрического тока.',
                'description_en' => 'Treatment using electric current.',
                'is_active' => true,
            ],
            [
                'department_id' => 2,
                'name_uz' => 'Magnitoterapiya',
                'name_ru' => 'Магнитотерапия',
                'name_en' => 'Magnetotherapy',
                'category' => 'therapy',
                'price' => 22.00,
                'duration' => 25,
                'description_uz' => 'Magnit maydon yordamida davolash.',
                'description_ru' => 'Лечение магнитным полем.',
                'description_en' => 'Treatment using magnetic field.',
                'is_active' => true,
            ],
            [
                'department_id' => 2,
                'name_uz' => 'EEG',
                'name_ru' => 'ЭЭГ',
                'name_en' => 'Electroencephalography',
                'category' => 'diagnostic',
                'price' => 35.00,
                'duration' => 30,
                'description_uz' => 'Bosh miya elektr faolligini tekshirish.',
                'description_ru' => 'Исследование электрической активности мозга.',
                'description_en' => 'Brain electrical activity examination.',
                'is_active' => true,
            ],
        
            // ==================== ENDOKRINOLOGIYA ====================
            [
                'department_id' => 3,
                'name_uz' => 'Insulin terapiyasi',
                'name_ru' => 'Инсулинотерапия',
                'name_en' => 'Insulin Therapy',
                'category' => 'therapy',
                'price' => 30.00,
                'duration' => 20,
                'description_uz' => 'Insulin yuborish muolajasi.',
                'description_ru' => 'Процедура введения инсулина.',
                'description_en' => 'Insulin administration procedure.',
                'is_active' => true,
            ],
            [
                'department_id' => 3,
                'name_uz' => 'Qand miqdorini nazorat qilish',
                'name_ru' => 'Контроль уровня сахара',
                'name_en' => 'Blood Sugar Monitoring',
                'category' => 'diagnostic',
                'price' => 10.00,
                'duration' => 10,
                'description_uz' => 'Qondagi glyukoza darajasini tekshirish.',
                'description_ru' => 'Проверка уровня глюкозы в крови.',
                'description_en' => 'Blood glucose level check.',
                'is_active' => true,
            ],
            [
                'department_id' => 3,
                'name_uz' => 'Gormon terapiyasi',
                'name_ru' => 'Гормональная терапия',
                'name_en' => 'Hormone Therapy',
                'category' => 'therapy',
                'price' => 40.00,
                'duration' => 25,
                'description_uz' => 'Gormon preparatlari bilan davolash.',
                'description_ru' => 'Лечение гормональными препаратами.',
                'description_en' => 'Treatment with hormone medications.',
                'is_active' => true,
            ],
        
            // ==================== OFTALMOLOGIYA ====================
            [
                'department_id' => 4,
                'name_uz' => 'Ko\'z lazer terapiyasi',
                'name_ru' => 'Лазерная терапия глаз',
                'name_en' => 'Eye Laser Therapy',
                'category' => 'therapy',
                'price' => 55.00,
                'duration' => 20,
                'description_uz' => 'Ko\'z kasalliklarini lazer yordamida davolash.',
                'description_ru' => 'Лечение глазных заболеваний лазером.',
                'description_en' => 'Laser treatment for eye diseases.',
                'is_active' => true,
            ],
            [
                'department_id' => 4,
                'name_uz' => 'Ko\'z bosimini o\'lchash',
                'name_ru' => 'Измерение глазного давления',
                'name_en' => 'Eye Pressure Measurement',
                'category' => 'diagnostic',
                'price' => 15.00,
                'duration' => 10,
                'description_uz' => 'Glaukoma diagnostikasi uchun.',
                'description_ru' => 'Для диагностики глаукомы.',
                'description_en' => 'For glaucoma diagnosis.',
                'is_active' => true,
            ],
            [
                'department_id' => 4,
                'name_uz' => 'Ko\'z yuvish',
                'name_ru' => 'Промывание глаз',
                'name_en' => 'Eye Irrigation',
                'category' => 'therapy',
                'price' => 12.00,
                'duration' => 10,
                'description_uz' => 'Ko\'zni antiseptik eritma bilan yuvish.',
                'description_ru' => 'Промывание глаз антисептическим раствором.',
                'description_en' => 'Eye irrigation with antiseptic solution.',
                'is_active' => true,
            ],
        
            // ==================== LOR ====================
            [
                'department_id' => 5,
                'name_uz' => 'Quloq yuvish',
                'name_ru' => 'Промывание уха',
                'name_en' => 'Ear Irrigation',
                'category' => 'therapy',
                'price' => 15.00,
                'duration' => 15,
                'description_uz' => 'Quloq kanalini tozalash.',
                'description_ru' => 'Очистка слухового прохода.',
                'description_en' => 'Cleaning the ear canal.',
                'is_active' => true,
            ],
            [
                'department_id' => 5,
                'name_uz' => 'Burun yuvish',
                'name_ru' => 'Промывание носа',
                'name_en' => 'Nasal Irrigation',
                'category' => 'therapy',
                'price' => 14.00,
                'duration' => 10,
                'description_uz' => 'Burun bo\'shlig\'ini yuvish.',
                'description_ru' => 'Промывание полости носа.',
                'description_en' => 'Nasal cavity irrigation.',
                'is_active' => true,
            ],
            [
                'department_id' => 5,
                'name_uz' => 'Ingalyatsiya',
                'name_ru' => 'Ингаляция',
                'name_en' => 'Inhalation Therapy',
                'category' => 'therapy',
                'price' => 18.00,
                'duration' => 20,
                'description_uz' => 'Nafas yo\'llarini davolash.',
                'description_ru' => 'Лечение дыхательных путей.',
                'description_en' => 'Respiratory therapy.',
                'is_active' => true,
            ],
        
            // ==================== PEDIATRIYA ====================
            [
                'department_id' => 6,
                'name_uz' => 'Nebulayzer terapiyasi',
                'name_ru' => 'Небулайзерная терапия',
                'name_en' => 'Nebulizer Therapy',
                'category' => 'therapy',
                'price' => 16.00,
                'duration' => 15,
                'description_uz' => 'Bolalar uchun ingalyatsiya.',
                'description_ru' => 'Ингаляция для детей.',
                'description_en' => 'Inhalation therapy for children.',
                'is_active' => true,
            ],
            [
                'department_id' => 6,
                'name_uz' => 'Bolalar massaji',
                'name_ru' => 'Детский массаж',
                'name_en' => 'Pediatric Massage',
                'category' => 'therapy',
                'price' => 25.00,
                'duration' => 30,
                'description_uz' => 'Bolalar uchun davolovchi massaj.',
                'description_ru' => 'Лечебный массаж для детей.',
                'description_en' => 'Therapeutic massage for children.',
                'is_active' => true,
            ],
            [
                'department_id' => 6,
                'name_uz' => 'Vitamin infuziyasi',
                'name_ru' => 'Витаминная инфузия',
                'name_en' => 'Vitamin Infusion',
                'category' => 'therapy',
                'price' => 28.00,
                'duration' => 25,
                'description_uz' => 'Vitaminlarni tomir orqali yuborish.',
                'description_ru' => 'Введение витаминов внутривенно.',
                'description_en' => 'Intravenous vitamin administration.',
                'is_active' => true,
            ],
        
            // ==================== PSIXIATRIYA ====================
            [
                'department_id' => 7,
                'name_uz' => 'Individual psixoterapiya',
                'name_ru' => 'Индивидуальная психотерапия',
                'name_en' => 'Individual Psychotherapy',
                'category' => 'therapy',
                'price' => 60.00,
                'duration' => 60,
                'description_uz' => 'Shaxsiy psixoterapiya seansi.',
                'description_ru' => 'Индивидуальный сеанс психотерапии.',
                'description_en' => 'Individual psychotherapy session.',
                'is_active' => true,
            ],
            [
                'department_id' => 7,
                'name_uz' => 'Guruh terapiyasi',
                'name_ru' => 'Групповая терапия',
                'name_en' => 'Group Therapy',
                'category' => 'therapy',
                'price' => 35.00,
                'duration' => 90,
                'description_uz' => 'Guruh bilan psixologik davolash.',
                'description_ru' => 'Групповая психологическая терапия.',
                'description_en' => 'Psychological therapy in a group.',
                'is_active' => true,
            ],
            [
                'department_id' => 7,
                'name_uz' => 'Relaksatsiya terapiyasi',
                'name_ru' => 'Релаксационная терапия',
                'name_en' => 'Relaxation Therapy',
                'category' => 'therapy',
                'price' => 30.00,
                'duration' => 40,
                'description_uz' => 'Stressni kamaytirish terapiyasi.',
                'description_ru' => 'Терапия для снижения стресса.',
                'description_en' => 'Therapy for stress reduction.',
                'is_active' => true,
            ],
        ];

        foreach ($procedures as $procedure) {
            Procedure::create($procedure);
        }
    }
}