<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TestSeeder extends Seeder
{
    public function run()
    {
        // =============================================
        // 1. TESTLAR (60 ta test)
        // =============================================
        
        $tests = [
            // ===== GEMATOLOGIYA (Qon) - 10 ta =====
            [
                'name' => 'Gemoglobin',
                'code' => 'HGB',
                'unit' => 'g/dL',
                'normal_min' => 13.00,
                'normal_max' => 17.00,
                'price' => 30,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Eritrositlar',
                'code' => 'RBC',
                'unit' => '10^12/L',
                'normal_min' => 4.50,
                'normal_max' => 5.90,
                'price' => 25,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Gematokrit',
                'code' => 'HCT',
                'unit' => '%',
                'normal_min' => 40.00,
                'normal_max' => 52.00,
                'price' => 20,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Leykotsitlar',
                'code' => 'WBC',
                'unit' => '10^9/L',
                'normal_min' => 4.50,
                'normal_max' => 11.00,
                'price' => 25,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Trombotsitlar',
                'code' => 'PLT',
                'unit' => '10^9/L',
                'normal_min' => 150.00,
                'normal_max' => 400.00,
                'price' => 25,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Neytrofillar',
                'code' => 'NEUT',
                'unit' => '%',
                'normal_min' => 40.00,
                'normal_max' => 75.00,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Limfotsitlar',
                'code' => 'LYMPH',
                'unit' => '%',
                'normal_min' => 20.00,
                'normal_max' => 45.00,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Monotsitlar',
                'code' => 'MONO',
                'unit' => '%',
                'normal_min' => 2.00,
                'normal_max' => 10.00,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Eozinofillar',
                'code' => 'EO',
                'unit' => '%',
                'normal_min' => 1.00,
                'normal_max' => 6.00,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Bazofillar',
                'code' => 'BASO',
                'unit' => '%',
                'normal_min' => 0.00,
                'normal_max' => 2.00,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],

            // ===== BIOKIMYO - 15 ta =====
            [
                'name' => 'Glyukoza',
                'code' => 'GLU',
                'unit' => 'mmol/L',
                'normal_min' => 3.90,
                'normal_max' => 5.60,
                'price' => 35,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Kreatinin',
                'code' => 'CRE',
                'unit' => 'µmol/L',
                'normal_min' => 60.00,
                'normal_max' => 110.00,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Mochevina',
                'code' => 'UREA',
                'unit' => 'mmol/L',
                'normal_min' => 2.50,
                'normal_max' => 7.50,
                'price' => 35,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Natriy',
                'code' => 'NA',
                'unit' => 'mmol/L',
                'normal_min' => 135.00,
                'normal_max' => 145.00,
                'price' => 30,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Kaliy',
                'code' => 'K',
                'unit' => 'mmol/L',
                'normal_min' => 3.50,
                'normal_max' => 5.10,
                'price' => 30,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Xlor',
                'code' => 'CL',
                'unit' => 'mmol/L',
                'normal_min' => 98.00,
                'normal_max' => 106.00,
                'price' => 30,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Kalsiy',
                'code' => 'CA',
                'unit' => 'mmol/L',
                'normal_min' => 2.10,
                'normal_max' => 2.60,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Fosfor',
                'code' => 'P',
                'unit' => 'mmol/L',
                'normal_min' => 0.80,
                'normal_max' => 1.50,
                'price' => 35,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Temir',
                'code' => 'FE',
                'unit' => 'µmol/L',
                'normal_min' => 10.00,
                'normal_max' => 30.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Albumin',
                'code' => 'ALB',
                'unit' => 'g/L',
                'normal_min' => 35.00,
                'normal_max' => 50.00,
                'price' => 35,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Bilirubin',
                'code' => 'BIL',
                'unit' => 'µmol/L',
                'normal_min' => 3.40,
                'normal_max' => 20.50,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'ALT',
                'code' => 'ALT',
                'unit' => 'U/L',
                'normal_min' => 0.00,
                'normal_max' => 41.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'AST',
                'code' => 'AST',
                'unit' => 'U/L',
                'normal_min' => 0.00,
                'normal_max' => 40.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'ALP',
                'code' => 'ALP',
                'unit' => 'U/L',
                'normal_min' => 44.00,
                'normal_max' => 147.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'GGT',
                'code' => 'GGT',
                'unit' => 'U/L',
                'normal_min' => 0.00,
                'normal_max' => 61.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],

            // ===== GORMONLAR - 8 ta =====
            [
                'name' => 'TSH',
                'code' => 'TSH',
                'unit' => 'mIU/L',
                'normal_min' => 0.40,
                'normal_max' => 4.00,
                'price' => 60,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'T4',
                'code' => 'T4',
                'unit' => 'pmol/L',
                'normal_min' => 11.00,
                'normal_max' => 23.00,
                'price' => 55,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'T3',
                'code' => 'T3',
                'unit' => 'nmol/L',
                'normal_min' => 1.30,
                'normal_max' => 3.10,
                'price' => 55,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Kortizol',
                'code' => 'CORT',
                'unit' => 'nmol/L',
                'normal_min' => 140.00,
                'normal_max' => 600.00,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Testosteron',
                'code' => 'TEST',
                'unit' => 'nmol/L',
                'normal_min' => 8.00,
                'normal_max' => 29.00,
                'price' => 80,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Estradiol',
                'code' => 'E2',
                'unit' => 'pmol/L',
                'normal_min' => 40.00,
                'normal_max' => 160.00,
                'price' => 75,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Progesteron',
                'code' => 'PROG',
                'unit' => 'nmol/L',
                'normal_min' => 0.00,
                'normal_max' => 0.50,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Prolaktin',
                'code' => 'PRL',
                'unit' => 'mIU/L',
                'normal_min' => 70.00,
                'normal_max' => 400.00,
                'price' => 65,
                'duration' => 3,
                'is_active' => 1,
            ],

            // ===== INFEKTSION - 7 ta =====
            [
                'name' => 'CRP',
                'code' => 'CRP',
                'unit' => 'mg/L',
                'normal_min' => 0.00,
                'normal_max' => 5.00,
                'price' => 50,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'ESR',
                'code' => 'ESR',
                'unit' => 'mm/h',
                'normal_min' => 0.00,
                'normal_max' => 20.00,
                'price' => 25,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Prokaltsitonin',
                'code' => 'PCT',
                'unit' => 'ng/mL',
                'normal_min' => 0.00,
                'normal_max' => 0.50,
                'price' => 90,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'LDH',
                'code' => 'LDH',
                'unit' => 'U/L',
                'normal_min' => 140.00,
                'normal_max' => 280.00,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'CK',
                'code' => 'CK',
                'unit' => 'U/L',
                'normal_min' => 25.00,
                'normal_max' => 200.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Ferritin',
                'code' => 'FERR',
                'unit' => 'ng/mL',
                'normal_min' => 30.00,
                'normal_max' => 400.00,
                'price' => 55,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Vitamin B12',
                'code' => 'B12',
                'unit' => 'pg/mL',
                'normal_min' => 200.00,
                'normal_max' => 900.00,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],

            // ===== QO'SHIMCHA TESTLAR - 10 ta =====
            [
                'name' => 'D vitamini',
                'code' => 'VITD',
                'unit' => 'ng/mL',
                'normal_min' => 20.00,
                'normal_max' => 60.00,
                'price' => 80,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Folin kislota',
                'code' => 'FOL',
                'unit' => 'ng/mL',
                'normal_min' => 3.00,
                'normal_max' => 20.00,
                'price' => 65,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Insulin',
                'code' => 'INS',
                'unit' => 'µIU/mL',
                'normal_min' => 2.60,
                'normal_max' => 25.00,
                'price' => 75,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'A1C (Glykohemoglobin)',
                'code' => 'HBA1C',
                'unit' => '%',
                'normal_min' => 4.00,
                'normal_max' => 6.00,
                'price' => 60,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Homosistein',
                'code' => 'HCY',
                'unit' => 'µmol/L',
                'normal_min' => 5.00,
                'normal_max' => 15.00,
                'price' => 80,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'IgE',
                'code' => 'IGE',
                'unit' => 'IU/mL',
                'normal_min' => 0.00,
                'normal_max' => 100.00,
                'price' => 90,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'IgG',
                'code' => 'IGG',
                'unit' => 'g/L',
                'normal_min' => 7.00,
                'normal_max' => 16.00,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'IgM',
                'code' => 'IGM',
                'unit' => 'g/L',
                'normal_min' => 0.40,
                'normal_max' => 2.50,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'IgA',
                'code' => 'IGA',
                'unit' => 'g/L',
                'normal_min' => 0.80,
                'normal_max' => 4.00,
                'price' => 70,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Rheumatoid faktor',
                'code' => 'RF',
                'unit' => 'IU/mL',
                'normal_min' => 0.00,
                'normal_max' => 14.00,
                'price' => 85,
                'duration' => 3,
                'is_active' => 1,
            ],
            [
                'name' => 'Fibrinogen',
                'code' => 'FIB',
                'unit' => 'g/L',
                'normal_min' => 2.00,
                'normal_max' => 4.00,
                'price' => 50,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Protrombin vaqti',
                'code' => 'PT',
                'unit' => 's',
                'normal_min' => 11.00,
                'normal_max' => 15.00,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'APTT',
                'code' => 'APTT',
                'unit' => 's',
                'normal_min' => 25.00,
                'normal_max' => 35.00,
                'price' => 40,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Protein',
                'code' => 'PRO',
                'unit' => 'g/L',
                'normal_min' => 0.00,
                'normal_max' => 0.15,
                'price' => 25,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Leykotsitlar (siydik)',
                'code' => 'LEU',
                'unit' => 'cells/µL',
                'normal_min' => 0.00,
                'normal_max' => 10.00,
                'price' => 20,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Nitrit',
                'code' => 'NIT',
                'unit' => '-',
                'normal_min' => null,
                'normal_max' => null,
                'price' => 15,
                'duration' => 1,
                'is_active' => 1,
            ],
            [
                'name' => 'Troponin',
                'code' => 'TROP',
                'unit' => 'ng/mL',
                'normal_min' => 0.00,
                'normal_max' => 0.04,
                'price' => 100,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Globulin',
                'code' => 'GLOB',
                'unit' => 'g/L',
                'normal_min' => 20.00,
                'normal_max' => 35.00,
                'price' => 30,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'A/G nisbati',
                'code' => 'A/G',
                'unit' => '-',
                'normal_min' => 1.20,
                'normal_max' => 2.20,
                'price' => 25,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Amilaza',
                'code' => 'AMY',
                'unit' => 'U/L',
                'normal_min' => 30.00,
                'normal_max' => 120.00,
                'price' => 45,
                'duration' => 2,
                'is_active' => 1,
            ],
            [
                'name' => 'Lipaza',
                'code' => 'LIP',
                'unit' => 'U/L',
                'normal_min' => 0.00,
                'normal_max' => 60.00,
                'price' => 50,
                'duration' => 2,
                'is_active' => 1,
            ],
        ];

        // Testlarni saqlash va ID larni olish
        $testIds = [];
        foreach ($tests as $test) {
            $id = DB::table('tests')->insertGetId([
                'name' => $test['name'],
                'code' => $test['code'],
                'unit' => $test['unit'],
                'normal_min' => $test['normal_min'],
                'normal_max' => $test['normal_max'],
                'price' => $test['price'],
                'duration' => $test['duration'],
                'is_active' => $test['is_active'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
            $testIds[$test['code']] = $id;
        }

        // =============================================
        // 2. PANELLAR (25 ta panel) - har birida 10-15 ta test
        // =============================================
        
        $panels = [
            [
                'name_uz' => 'Umumiy Qon Tekshiruvi',
                'name_ru' => 'Общий Анализ Крови',
                'name_en' => 'Complete Blood Count',
                'code' => 'CBC',
                'price' => 120,
                'time' => 2,
                'description_uz' => 'Qonning barcha asosiy ko\'rsatkichlarini o\'z ichiga oladi',
                'description_ru' => 'Включает все основные показатели крови',
                'description_en' => 'Includes all basic blood parameters',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['HGB', 'RBC', 'HCT', 'WBC', 'PLT', 'NEUT', 'LYMPH', 'MONO', 'EO', 'BASO']
            ],
            [
                'name_uz' => 'Jigar Profili',
                'name_ru' => 'Печеночный Профиль',
                'name_en' => 'Liver Profile',
                'code' => 'LIV',
                'price' => 150,
                'time' => 3,
                'description_uz' => 'Jigar funksiyasini baholaydigan testlar',
                'description_ru' => 'Тесты для оценки функции печени',
                'description_en' => 'Tests assessing liver function',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['ALB', 'BIL', 'ALT', 'AST', 'ALP', 'GGT', 'LDH', 'GLOB', 'A/G']
            ],
            [
                'name_uz' => 'Buyrak Profili',
                'name_ru' => 'Почечный Профиль',
                'name_en' => 'Renal Profile',
                'code' => 'REN',
                'price' => 140,
                'time' => 3,
                'description_uz' => 'Buyrak funksiyasini baholaydigan testlar',
                'description_ru' => 'Тесты для оценки функции почек',
                'description_en' => 'Tests assessing kidney function',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['CRE', 'UREA', 'NA', 'K', 'CL', 'CA', 'P', 'ALB', 'GLU', 'PRO']
            ],
            [
                'name_uz' => 'Elektrolitlar Profili',
                'name_ru' => 'Электролитный Профиль',
                'name_en' => 'Electrolyte Profile',
                'code' => 'ELE',
                'price' => 100,
                'time' => 2,
                'description_uz' => 'Qondagi elektrolitlar darajasini baholash',
                'description_ru' => 'Оценка уровня электролитов в крови',
                'description_en' => 'Assessment of blood electrolyte levels',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['NA', 'K', 'CL', 'CA', 'P', 'MG', 'FE', 'GLU', 'ALB', 'CRE']
            ],
            [
                'name_uz' => 'Temir Metabolizmi Profili',
                'name_ru' => 'Профиль Метаболизма Железа',
                'name_en' => 'Iron Metabolism Profile',
                'code' => 'IRN',
                'price' => 130,
                'time' => 3,
                'description_uz' => 'Temir metabolizmini baholaydigan testlar',
                'description_ru' => 'Тесты для оценки метаболизма железа',
                'description_en' => 'Tests assessing iron metabolism',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['FE', 'FERR', 'HGB', 'HCT', 'RBC', 'B12', 'FOL', 'VITD', 'ALB', 'CRE']
            ],
            [
                'name_uz' => 'Qalqonsimon Bez Profili',
                'name_ru' => 'Тиреоидный Профиль',
                'name_en' => 'Thyroid Profile',
                'code' => 'THY',
                'price' => 160,
                'time' => 4,
                'description_uz' => 'Qalqonsimon bez funksiyasini baholash',
                'description_ru' => 'Оценка функции щитовидной железы',
                'description_en' => 'Assessment of thyroid function',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['TSH', 'T4', 'T3', 'CORT', 'PRL', 'TEST', 'E2', 'PROG', 'GLU', 'INS']
            ],
            [
                'name_uz' => 'Jinsiy Gormonlar Profili (Erkak)',
                'name_ru' => 'Профиль Половых Гормонов (Мужчина)',
                'name_en' => 'Sex Hormone Profile (Male)',
                'code' => 'SHM',
                'price' => 200,
                'time' => 4,
                'description_uz' => 'Erkak jinsiy gormonlarini baholash',
                'description_ru' => 'Оценка мужских половых гормонов',
                'description_en' => 'Assessment of male sex hormones',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['TEST', 'TSH', 'T4', 'T3', 'PRL', 'E2', 'PROG', 'CORT', 'GLU', 'INS']
            ],
            [
                'name_uz' => 'Jinsiy Gormonlar Profili (Ayol)',
                'name_ru' => 'Профиль Половых Гормонов (Женщина)',
                'name_en' => 'Sex Hormone Profile (Female)',
                'code' => 'SHF',
                'price' => 200,
                'time' => 4,
                'description_uz' => 'Ayol jinsiy gormonlarini baholash',
                'description_ru' => 'Оценка женских половых гормонов',
                'description_en' => 'Assessment of female sex hormones',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['E2', 'PROG', 'PRL', 'TSH', 'T4', 'T3', 'TEST', 'CORT', 'GLU', 'INS']
            ],
            [
                'name_uz' => 'Infeksion Markerlar Profili',
                'name_ru' => 'Профиль Инфекционных Маркеров',
                'name_en' => 'Infection Marker Profile',
                'code' => 'INF',
                'price' => 180,
                'time' => 3,
                'description_uz' => 'Infeksion holatni baholaydigan testlar',
                'description_ru' => 'Тесты для оценки инфекционного состояния',
                'description_en' => 'Tests assessing infection status',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['CRP', 'ESR', 'PCT', 'WBC', 'NEUT', 'LYMPH', 'MONO', 'EO', 'BASO', 'LDH']
            ],
            [
                'name_uz' => 'Yallig\'lanish Profili',
                'name_ru' => 'Профиль Воспаления',
                'name_en' => 'Inflammation Profile',
                'code' => 'INFLA',
                'price' => 160,
                'time' => 3,
                'description_uz' => 'Yallig\'lanish darajasini baholaydigan testlar',
                'description_ru' => 'Тесты для оценки уровня воспаления',
                'description_en' => 'Tests assessing inflammation level',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['CRP', 'ESR', 'LDH', 'ALB', 'GLOB', 'A/G', 'FE', 'FERR', 'WBC', 'PLT']
            ],
            [
                'name_uz' => 'Enzim Profili',
                'name_ru' => 'Ферментный Профиль',
                'name_en' => 'Enzyme Profile',
                'code' => 'ENZ',
                'price' => 130,
                'time' => 3,
                'description_uz' => 'Muhim enzimlar darajasini baholash',
                'description_ru' => 'Оценка уровня важных ферментов',
                'description_en' => 'Assessment of important enzyme levels',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['ALT', 'AST', 'ALP', 'GGT', 'LDH', 'CK', 'AMY', 'LIP', 'ALB', 'BIL']
            ],
            [
                'name_uz' => 'Karbonhidrat Metabolizmi Profili',
                'name_ru' => 'Профиль Углеводного Обмена',
                'name_en' => 'Carbohydrate Metabolism Profile',
                'code' => 'CARB',
                'price' => 140,
                'time' => 3,
                'description_uz' => 'Uglevod metabolizmini baholash',
                'description_ru' => 'Оценка углеводного обмена',
                'description_en' => 'Assessment of carbohydrate metabolism',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['GLU', 'HBA1C', 'INS', 'CRE', 'UREA', 'NA', 'K', 'CL', 'CA', 'P']
            ],
            [
                'name_uz' => 'Protein Metabolizmi Profili',
                'name_ru' => 'Профиль Белкового Обмена',
                'name_en' => 'Protein Metabolism Profile',
                'code' => 'PROT',
                'price' => 120,
                'time' => 3,
                'description_uz' => 'Protein metabolizmini baholash',
                'description_ru' => 'Оценка белкового обмена',
                'description_en' => 'Assessment of protein metabolism',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['ALB', 'CRE', 'UREA', 'GLOB', 'A/G', 'BIL', 'ALT', 'AST', 'LDH', 'FE']
            ],
            [
                'name_uz' => 'Vitamin Profili',
                'name_ru' => 'Витаминный Профиль',
                'name_en' => 'Vitamin Profile',
                'code' => 'VIT',
                'price' => 200,
                'time' => 4,
                'description_uz' => 'Muhim vitaminlar darajasini baholash',
                'description_ru' => 'Оценка уровня важных витаминов',
                'description_en' => 'Assessment of important vitamin levels',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['VITD', 'FOL', 'B12', 'FE', 'HGB', 'RBC', 'HCT', 'CA', 'P', 'MG']
            ],
            [
                'name_uz' => 'Immunoglobulin Profili',
                'name_ru' => 'Иммуноглобулиновый Профиль',
                'name_en' => 'Immunoglobulin Profile',
                'code' => 'IG',
                'price' => 200,
                'time' => 4,
                'description_uz' => 'Immunoglobulinlar darajasini baholash',
                'description_ru' => 'Оценка уровня иммуноглобулинов',
                'description_en' => 'Assessment of immunoglobulin levels',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['IGG', 'IGM', 'IGA', 'IGE', 'CRP', 'ESR', 'RF', 'WBC', 'LYMPH', 'ALB']
            ],
            [
                'name_uz' => 'Qon Koagulyatsiya Profili',
                'name_ru' => 'Профиль Коагуляции Крови',
                'name_en' => 'Blood Coagulation Profile',
                'code' => 'COAG',
                'price' => 150,
                'time' => 3,
                'description_uz' => 'Qon ivish tizimini baholash',
                'description_ru' => 'Оценка системы свертывания крови',
                'description_en' => 'Assessment of blood clotting system',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['PLT', 'FIB', 'PT', 'APTT', 'HGB', 'HCT', 'RBC', 'WBC', 'CRP', 'ALB']
            ],
            [
                'name_uz' => 'Siydik Tahlili',
                'name_ru' => 'Анализ Мочи',
                'name_en' => 'Urine Analysis',
                'code' => 'URINE',
                'price' => 80,
                'time' => 2,
                'description_uz' => 'Siydikning umumiy tahlili',
                'description_ru' => 'Общий анализ мочи',
                'description_en' => 'Complete urine analysis',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['GLU', 'PRO', 'BIL', 'LEU', 'NIT', 'CRE', 'UREA', 'NA', 'K', 'CL']
            ],
            [
                'name_uz' => 'Yurak Markerlar Profili',
                'name_ru' => 'Профиль Сердечных Маркеров',
                'name_en' => 'Cardiac Marker Profile',
                'code' => 'CARD',
                'price' => 220,
                'time' => 4,
                'description_uz' => 'Yurak xastaliklarini baholaydigan markerlar',
                'description_ru' => 'Маркеры для оценки сердечных заболеваний',
                'description_en' => 'Markers for assessing cardiac conditions',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['TROP', 'CK', 'LDH', 'BIL', 'ALT', 'AST', 'CRP', 'WBC', 'NA', 'K', 'CL', 'CA', 'P']
            ],
            [
                'name_uz' => 'Oqsil Fraksiyalari Profili',
                'name_ru' => 'Профиль Белковых Фракций',
                'name_en' => 'Protein Fraction Profile',
                'code' => 'PROTF',
                'price' => 160,
                'time' => 4,
                'description_uz' => 'Oqsil fraksiyalarini baholash',
                'description_ru' => 'Оценка белковых фракций',
                'description_en' => 'Assessment of protein fractions',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['ALB', 'GLOB', 'A/G', 'LDH', 'BIL', 'ALT', 'AST', 'ALP', 'GGT', 'CRE', 'UREA']
            ],
            [
                'name_uz' => 'Oshqozon-ichak Profili',
                'name_ru' => 'Профиль ЖКТ',
                'name_en' => 'Gastrointestinal Profile',
                'code' => 'GI',
                'price' => 190,
                'time' => 4,
                'description_uz' => 'Oshqozon-ichak tizimini baholash',
                'description_ru' => 'Оценка желудочно-кишечного тракта',
                'description_en' => 'Assessment of gastrointestinal tract',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['ALB', 'BIL', 'ALT', 'AST', 'AMY', 'LIP', 'GGT', 'ALP', 'CRE', 'UREA', 'NA', 'K', 'CL']
            ],
            [
                'name_uz' => 'Metabolik Profil (Kengaytirilgan)',
                'name_ru' => 'Метаболический Профиль (Расширенный)',
                'name_en' => 'Metabolic Profile (Extended)',
                'code' => 'METAB',
                'price' => 250,
                'time' => 5,
                'description_uz' => 'Kengaytirilgan metabolik baholash',
                'description_ru' => 'Расширенная метаболическая оценка',
                'description_en' => 'Extended metabolic assessment',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['GLU', 'HBA1C', 'INS', 'CRE', 'UREA', 'NA', 'K', 'CA', 'P', 'ALB', 'BIL', 'ALT', 'AST', 'LDH', 'CK']
            ],
            [
                'name_uz' => 'Anemiya Profili',
                'name_ru' => 'Профиль Анемии',
                'name_en' => 'Anemia Profile',
                'code' => 'ANEM',
                'price' => 180,
                'time' => 4,
                'description_uz' => 'Anemiyani baholaydigan testlar',
                'description_ru' => 'Тесты для оценки анемии',
                'description_en' => 'Tests for anemia assessment',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['HGB', 'HCT', 'RBC', 'FE', 'FERR', 'B12', 'FOL', 'VITD', 'WBC', 'PLT', 'LDH', 'ESR', 'CRP']
            ],
            [
                'name_uz' => 'Infektsion Kasalliklar Profili',
                'name_ru' => 'Профиль Инфекционных Заболеваний',
                'name_en' => 'Infectious Disease Profile',
                'code' => 'INFEC',
                'price' => 250,
                'time' => 5,
                'description_uz' => 'Infektsion kasalliklarni aniqlash',
                'description_ru' => 'Выявление инфекционных заболеваний',
                'description_en' => 'Detection of infectious diseases',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['CRP', 'PCT', 'WBC', 'NEUT', 'LYMPH', 'MONO', 'EO', 'BASO', 'ESR', 'IGG', 'IGM', 'IGA', 'LDH']
            ],
            [
                'name_uz' => 'Diabet Profili',
                'name_ru' => 'Диабет Профиль',
                'name_en' => 'Diabetes Profile',
                'code' => 'DIAB',
                'price' => 160,
                'time' => 3,
                'description_uz' => 'Qandli diabetni baholash',
                'description_ru' => 'Оценка сахарного диабета',
                'description_en' => 'Assessment of diabetes',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['GLU', 'HBA1C', 'INS', 'CRE', 'UREA', 'NA', 'K', 'CL', 'CA', 'P', 'ALB']
            ],
            [
                'name_uz' => 'Autoimmun Kasalliklar Profili',
                'name_ru' => 'Профиль Аутоиммунных Заболеваний',
                'name_en' => 'Autoimmune Disease Profile',
                'code' => 'AUTO',
                'price' => 280,
                'time' => 6,
                'description_uz' => 'Autoimmun kasalliklarni baholash',
                'description_ru' => 'Оценка аутоиммунных заболеваний',
                'description_en' => 'Assessment of autoimmune diseases',
                'department_id' => 1,
                'status' => 1,
                'tests' => ['RF', 'CRP', 'ESR', 'IGG', 'IGM', 'IGA', 'IGE', 'WBC', 'PLT', 'LDH', 'ALB', 'GLOB', 'A/G']
            ],
        ];

        // Panellarni saqlash va ID larni olish
        foreach ($panels as $panel) {
            $panelId = DB::table('panels')->insertGetId([
                'name_uz' => $panel['name_uz'],
                'name_ru' => $panel['name_ru'],
                'name_en' => $panel['name_en'],
                'code' => $panel['code'],
                'price' => $panel['price'],
                'time' => $panel['time'],
                'description_uz' => $panel['description_uz'],
                'description_ru' => $panel['description_ru'],
                'description_en' => $panel['description_en'],
                'department_id' => $panel['department_id'],
                'status' => $panel['status'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Panelga testlarni biriktirish
            foreach ($panel['tests'] as $testCode) {
                if (isset($testIds[$testCode])) {
                    DB::table('panel_tests')->insert([
                        'panel_id' => $panelId,
                        'test_id' => $testIds[$testCode],
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                }
            }
        }

        // =============================================
        // 3. ALOHIDA TESTLAR (Panelga biriktirilmagan)
        // =============================================
        // Bu testlar allaqachon testlar jadvalida bor,
        // ular panel_tests jadvaliga qo'shilmaydi
        // Alohida testlar: VITD, FOL, INS, HBA1C, HCY, IGE, IGG, IGM, IGA, RF
    }
}